# Generated by Django 6.0.3 on 2026-03-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstep',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
    ]
