# Generated by Django 6.0.3 on 2026-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectstep_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
