# Generated by Django 6.0.3 on 2026-03-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_clientcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectaccesslink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectstep',
            options={'ordering': ['step_order']},
        ),
        migrations.AlterUniqueTogether(
            name='projectstep',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='projectaccesslink',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectaccesslink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('delayed', 'En retard'), ('blocked', 'Bloqué'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstep',
            name='status',
            field=models.CharField(choices=[('not_started', 'Non démarrée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('delayed', 'En retard'), ('blocked', 'Bloquée')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstep',
            name='step_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ClientContact',
        ),
    ]
