# Generated by Django 6.0.3 on 2026-03-23 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('project_created', 'Projet créé'), ('project_updated', 'Projet modifié'), ('project_cancelled', 'Projet annulé'), ('step_created', 'Étape créée'), ('step_updated', 'Étape modifiée'), ('step_deleted', 'Étape supprimée'), ('comment_created', 'Commentaire ajouté'), ('comment_updated', 'Commentaire modifié'), ('comment_deleted', 'Commentaire supprimé'), ('attachment_created', 'Pièce jointe ajoutée'), ('attachment_updated', 'Pièce jointe modifiée'), ('attachment_deleted', 'Pièce jointe supprimée')], max_length=50)),
                ('message', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
